### PR TITLE
Start a Scala 2.11 branch.

### PR DESCRIPTION
**Pull request by stephenh**
Hey; I'm poking around with Spark on Scala 2.11.

### CODE REVIEW

**Comment by ogrodnek** [comment]
Hey it looks like this will merge into master -- did you mean to submit a PR to a branch?

**Comment by stephenh** [comment]
I wasn't really sure how to make a not-to-master-PR... Feel free to not merge until we're more committed to 2.11.

**Comment by stephenh** [comment]
(I went ahead and pushed this into S3, so I'm not blocked; I'd been thinking I'd need you to push it to Maven central first.)

**Comment by pkallos** [comment]
:+1: any chance this can be merged + published?

**Comment by stephenh** [comment]
I finally figured out sbt publishing, so in theory this should be in Maven central soon-ish as com.bizo#spark-plug_2.11#1.2.6.

Instead of merging it into master, I'm going to keep a scala-2.11 branch for now, so will go ahead and close this PR.

**Pull request closed without merging**
